[build]
command = "echo 'no build needed'"
publish = "public"
functions = "netlify/functions"

[build.environment]
  PG_CONNECTION_STRING = "postgresql://neondb_owner:npg_sivB60ocWfPl@ep-wandering-violet-aeaez7lz-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
